### ISSUE TITLE
Vertretungsplan parsen

### ISSUE THREAD

**Issue by fxedel** [flogut/HGV-Android#3]
Genauso wie bei den Elternbriefen und wie auch schon in #2 beschrieben würde ich die Vertretungsplanereignisse parsen und stattdessen mit Views darstellen. Damit ist folgendes möglich:

- Umwandlung von Lehrer-Kürzel in Lehrer-Namen (Problem: Woher kennen wir die Kürzel? Hart reinkodieren? Im Elternportal findet man aber glaub ich nix)
- Aktualisierung im Hintergrund und Vergleich mit vorherigen Daten -> Wenn neue Ereignisse, Benachrichtigung anzeigen

**Comment by flogut** [comment]
Hier würde ich erstmal warten. Unser geschätzter Systemadmmin hat ja datenschutzrechtliche Bedenken, grade was die Speicherung von lehrerbezogenen Daten angeht. Ich würde erstmal, bis wir in ein paar Jahren mal ne Rückmeldung von ihm kriegen.
Das Parsen für die Darstellung können wir natürlich jetzt schon implementieren. Auch hier wieder: Wie würdest du es darstellen lassen? Hier sieht das HTML ja recht gut aus

**Comment by fxedel** [comment]
Man würde ja die Daten nur temporär speichern, vergangene Vertretungen werden gelöscht. Wenn das auch nicht geht macht das Parsen tatsächlich nicht viel Sinn, da die Darstellung wirklich schon ganz gut ausschaut.

**Comment by flogut** [comment]
Mal sehen, was Herr H. meint, wenn er in 4879 Jahren mal bereit ist, uns hier weiterzuhelfen...

**Comment by flogut** [comment]
Update: Wir sollten keinerlei Daten (außer den bereits jetzt gespeicherten) speichern. Das hier kannst du also vergessen.
